services:
  database:
    image: postgres:15-alpine
    container_name: revistuda-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1978"
      POSTGRES_DB: revistuda
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
